services:
  app:
    build: .
    container_name: qr-auth-app
    restart: always
    environment:
      - PORT=3000
      - HDREZKA_HOST=hdrezka.ag
    expose:
      - "3000"

  nginx:
    image: nginx:1.28-alpine3.23
    container_name: qr-auth-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    environment:
      - DOMAIN=${DOMAIN}
    depends_on:
      - app